### ISSUE TITLE
点开文件夹显示的图标与缩略图和默认图标不一样

### ISSUE THREAD

**Issue by wha4up** [zhihulite/Hydrogen#48]
![Screenshot_2024_0527_155342](https://github.com/huajiqaq/Hydrogen/assets/30365126/89d269ac-e5ff-45bd-bace-d3cdd4dd383c)

系统版本:origin安卓11
软件版本:最新版
复现操作:切换深色模式再切回

**Comment by huajiqaq** [comment]
另外 建议在https://huajiqaq.github.io/myhydrogen 下载最新版
