### ISSUE TITLE
升级最新版后内容加载不出来

### ISSUE THREAD

**Issue by 610364023** [zhihulite/Hydrogen#91]
卸载重装后也是如此，只有热榜能显示，但点进去就不行了
![Screenshot_2024-08-13-16-36-13-962_com zhihu hydrogen x](https://github.com/user-attachments/assets/7b7df85d-f82c-40b3-8e7a-95f890bc3ff9)
![Screenshot_2024-08-13-16-36-33-467_com zhihu hydrogen x](https://github.com/user-attachments/assets/83206bd5-288e-47e8-80f9-6c9ebeda9919)

**Comment by huajiqaq** [comment]
你上一个版本是多少 请问降级是否可以解决这个问题？ 你可通过[https//huajiqaq.github.io/myhydrogen/](https://huajiqaq.github.io/myhydrogen/update.html)
降级查看是否解决该问题

**Comment by huajiqaq** [comment]
可以把报错信息发过来吗

**Comment by huajiqaq** [comment]
似乎是api.zhihu.com 的问题 打开 https://api.zhihu.com/search/top_search 查看是否可访问 有可能是部分地区dns污染了

**Comment by huajiqaq** [comment]
估计你的地区部分知乎api被dns污染了 这种事之前发生在123网盘
